services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - APP_PORT=${APP_PORT}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    command: ["/bin/sh", "-c", "/app/run_app.sh"]
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
