"""Optimze database

Revision ID: e8a19d986c1c
Revises: 4a0976ded953
Create Date: 2024-09-04 18:10:40.998276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a19d986c1c'
down_revision: Union[str, None] = '4a0976ded953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_room_move')
    op.drop_constraint('moves_move_time_id_fkey', 'moves', type_='foreignkey')
    op.drop_column('moves', 'move_time_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('move_time_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('moves_move_time_id_fkey', 'moves', 'move_times', ['move_time_id'], ['id'])
    op.create_table('cinema_room_move',
    sa.Column('cinema_room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('move_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cinema_room_id'], ['cinema_rooms.id'], name='cinema_room_move_cinema_room_id_fkey'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], name='cinema_room_move_move_id_fkey')
    )
    # ### end Alembic commands ###
